module.exports = {
  ignoreFiles: ['node_modules/*', 'src/assets/**', 'build/**'],
  extends: ['stylelint-config-standard', 'stylelint-config-html/vue'],
  rules: {
    'selector-class-pattern': null,
    'max-nesting-depth': 6,
    'function-name-case': null,
    'selector-id-pattern': null,
    'selector-pseudo-element-no-unknown': null,
    'selector-max-compound-selectors': 6,
    'declaration-block-semicolon-newline-after': null,
    'keyframes-name-pattern': null,
    'custom-property-no-missing-var-function': null,
    'color-function-notation': 'legacy',
    'selector-no-qualifying-type': null,
    'max-line-length': null,
    'alpha-value-notation': 'number',
    'no-descending-specificity': null,
    'import-notation': 'string',
  },
}
